### ISSUE TITLE
namespaces configuration should not be fixed at build time for quarkus operator

### ISSUE THREAD

**Issue by aureamunoz** [snowdrop-zen/java-operator-sdk#1]
Hi,

I have an issue where I want a quarkus native executable to watch different namespaces depending on its environment variable.

The idea is to deploy a pod with env section something like

```yaml
env:
  - name: quarkus_operator_sdk_controllers_foocontroller.namespaces
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
```

or any other values.

Is it possible ?

---

https://github.com/java-operator-sdk/java-operator-sdk/issues/337

---

$upstream:337$
